# Generated by Django 3.0.3 on 2020-03-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken', '0005_auto_20200305_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfair',
            name='num_students_placed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobfair',
            name='num_students_registered',
            field=models.IntegerField(default=0),
        ),
    ]
