# Generated by Django 3.0.3 on 2020-03-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken', '0006_auto_20200313_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobfair',
            old_name='jobfair_date',
            new_name='jobfair_end_date',
        ),
        migrations.AddField(
            model_name='jobfair',
            name='jobfair_start_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
