# Generated by Django 3.0.3 on 2020-03-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken', '0008_auto_20200313_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfair',
            name='jobfair_end_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
